version: '3.9'

services:

  database:
    image: postgres:15.8
    ports:
      - 5432:5432
    volumes:
      - database_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  leeroy:
    build: .
    image: leeroy
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    links:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PASSWORD_HASH_SALT=DefaultPasswordHashSalt
      - JWT_SIGNATURE_SECRET=DefaultJSONWebTokenSignatureSecret
      - ACCESS_TOKEN_TTL_IN_MINUTES=60
      - REFRESH_TOKEN_TTL_IN_MINUTES=43200

volumes:
  database_storage:
