version: '3.9'

services:

  database:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - database_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  leeroy:
    build: https://github.com/podbolotov/Leeroy.git#main
    image: leeroy:1.0.0
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    links:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PASSWORD_HASH_SALT=DefaultPasswordHashSalt
      - JWT_SIGNATURE_SECRET=DefaultJSONWebTokenSignatureSecret
      - ACCESS_TOKEN_TTL_IN_MINUTES=60
      - REFRESH_TOKEN_TTL_IN_MINUTES=43200

  leeroy-api-tests:
    build: https://github.com/podbolotov/Leeroy-Api-Tests.git#main
    image: leeroy-api-tests:1.0.0
    depends_on:
      leeroy:
        condition: service_started
    links:
      - database
    environment:
      - APP_HOST=http://leeroy:8080
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PASSWORD_HASH_SALT=DefaultPasswordHashSalt
      - JWT_SIGNATURE_SECRET=DefaultJSONWebTokenSignatureSecret
      - ACCESS_TOKEN_TTL_IN_MINUTES=60
      - REFRESH_TOKEN_TTL_IN_MINUTES=43200
    volumes:
      - /home/debian/llce-t-reports:/code/allure-report
volumes:
  database_storage:
